### ISSUE TITLE
error downloading dataset

### ISSUE THREAD

**Issue by cenyuzhang** [dformoso/sklearn-classification#1]
I have the following error when trying to download the dataset. using python 3

<img width="1158" alt="error" src="https://user-images.githubusercontent.com/17069714/30331629-fcff6192-979d-11e7-9253-7ebe43244b2f.png">

**Comment by dformoso** [comment]
Yeap. I've tested the notebook on python 3 and it doesn't run. It's 2.7 for the moment. I'll update it eventually.

**Comment by dformoso** [comment]
Yeap. I've tested the notebook on python 3 and it doesn't run. It's 2.7 for the moment. I'll update it eventually.
